/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReservationRouteImport } from './routes/reservation'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DireitoDeImagemRouteImport } from './routes/direito-de-imagem'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AvaliacoesRouteImport } from './routes/avaliacoes'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReservationIndexRouteImport } from './routes/reservation.index'
import { Route as ContaIndexRouteImport } from './routes/conta.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ReservationVerifyEmailRouteImport } from './routes/reservation.verify-email'
import { Route as ReservationTermsRouteImport } from './routes/reservation.terms'
import { Route as ReservationSuccessRouteImport } from './routes/reservation.success'
import { Route as ReservationRegisterRouteImport } from './routes/reservation.register'
import { Route as ReservationCheckoutRouteImport } from './routes/reservation.checkout'
import { Route as ReciboNumberRouteImport } from './routes/recibo.$number'
import { Route as IndexnowSplatRouteImport } from './routes/indexnow.$'
import { Route as HospedagemWaySquadRouteImport } from './routes/hospedagem.way-squad'
import { Route as HospedagemWayConnectRouteImport } from './routes/hospedagem.way-connect'
import { Route as GrupoCouponRouteImport } from './routes/grupo.$coupon'
import { Route as ExperienciasTransferRouteImport } from './routes/experiencias.transfer'
import { Route as ExperienciasSlugRouteImport } from './routes/experiencias.$slug'
import { Route as ContaSegurancaRouteImport } from './routes/conta.seguranca'
import { Route as ContaPrivacidadeRouteImport } from './routes/conta.privacidade'
import { Route as ContaPerfilRouteImport } from './routes/conta.perfil'
import { Route as ContaPedidosRouteImport } from './routes/conta.pedidos'
import { Route as ContaNotificacoesRouteImport } from './routes/conta.notificacoes'
import { Route as ContaGruposRouteImport } from './routes/conta.grupos'
import { Route as CheckoutSucessoRouteImport } from './routes/checkout.sucesso'
import { Route as CheckoutPendenteRouteImport } from './routes/checkout.pendente'
import { Route as CheckoutFalhaRouteImport } from './routes/checkout.falha'
import { Route as CheckoutSlugRouteImport } from './routes/checkout.$slug'
import { Route as CdnSplatRouteImport } from './routes/cdn.$'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AvaliarOrderIdRouteImport } from './routes/avaliar.$orderId'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSegmentsRouteImport } from './routes/admin.segments'
import { Route as AdminSecurityRouteImport } from './routes/admin.security'
import { Route as AdminRoomsRouteImport } from './routes/admin.rooms'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminReservationsRouteImport } from './routes/admin.reservations'
import { Route as AdminReceiptsRouteImport } from './routes/admin.receipts'
import { Route as AdminReceiptTemplatesRouteImport } from './routes/admin.receipt-templates'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPagesRouteImport } from './routes/admin.pages'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminGroupsRouteImport } from './routes/admin.groups'
import { Route as AdminGatewaysRouteImport } from './routes/admin.gateways'
import { Route as AdminFiscalInvoicesRouteImport } from './routes/admin.fiscal-invoices'
import { Route as AdminFiscalRouteImport } from './routes/admin.fiscal'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminEmailTemplatesRouteImport } from './routes/admin.email-templates'
import { Route as AdminEmailProvidersRouteImport } from './routes/admin.email-providers'
import { Route as AdminEmailOutboxRouteImport } from './routes/admin.email-outbox'
import { Route as AdminDataCleanupRouteImport } from './routes/admin.data-cleanup'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminCheckinRouteImport } from './routes/admin.checkin'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAiProvidersRouteImport } from './routes/admin.ai-providers'
import { Route as ContaPedidosIndexRouteImport } from './routes/conta.pedidos.index'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin.settings.index'
import { Route as AdminPagesIndexRouteImport } from './routes/admin.pages.index'
import { Route as ContaPedidosIdRouteImport } from './routes/conta.pedidos.$id'
import { Route as AdminSettingsSeoRouteImport } from './routes/admin.settings.seo'
import { Route as AdminSettingsPageImagesRouteImport } from './routes/admin.settings.page-images'
import { Route as AdminSettingsIntegrationsRouteImport } from './routes/admin.settings.integrations'
import { Route as AdminSettingsGalleryRouteImport } from './routes/admin.settings.gallery'
import { Route as AdminSettingsBrandingRouteImport } from './routes/admin.settings.branding'
import { Route as AdminSettingsBackupRouteImport } from './routes/admin.settings.backup'
import { Route as AdminReceiptTemplatesIdRouteImport } from './routes/admin.receipt-templates_.$id'
import { Route as AdminProductsIdRouteImport } from './routes/admin.products_.$id'
import { Route as AdminPagesPageIdRouteImport } from './routes/admin.pages.$pageId'
import { Route as AdminOrdersIdRouteImport } from './routes/admin.orders_.$id'
import { Route as AdminGroupsIdRouteImport } from './routes/admin.groups_.$id'
import { Route as AdminGatewaysIdRouteImport } from './routes/admin.gateways_.$id'
import { Route as AdminGatewaysQaRouteImport } from './routes/admin.gateways.qa'
import { Route as AdminCustomersIdRouteImport } from './routes/admin.customers_.$id'
import { Route as AdminBlogPostIdRouteImport } from './routes/admin.blog_.$postId'
import { Route as ApiPublicWebhooksRetryRouteImport } from './routes/api/public/webhooks.retry'
import { Route as ApiPublicWebhooksProviderRouteImport } from './routes/api/public/webhooks.$provider'
import { Route as ApiPublicHooksSeoPingRouteImport } from './routes/api/public/hooks/seo-ping'
import { Route as ApiPublicHooksEventRemindersRouteImport } from './routes/api/public/hooks/event-reminders'
import { Route as ApiPublicHooksEmailDispatchRouteImport } from './routes/api/public/hooks/email-dispatch'
import { Route as ApiPublicAnalyticsPingRouteImport } from './routes/api/public/analytics/ping'
import { Route as ApiPublicAnalyticsIngestRouteImport } from './routes/api/public/analytics/ingest'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationRoute = ReservationRouteImport.update({
  id: '/reservation',
  path: '/reservation',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DireitoDeImagemRoute = DireitoDeImagemRouteImport.update({
  id: '/direito-de-imagem',
  path: '/direito-de-imagem',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AvaliacoesRoute = AvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationIndexRoute = ReservationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReservationRoute,
} as any)
const ContaIndexRoute = ContaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContaRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ReservationVerifyEmailRoute = ReservationVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => ReservationRoute,
} as any)
const ReservationTermsRoute = ReservationTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => ReservationRoute,
} as any)
const ReservationSuccessRoute = ReservationSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => ReservationRoute,
} as any)
const ReservationRegisterRoute = ReservationRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => ReservationRoute,
} as any)
const ReservationCheckoutRoute = ReservationCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => ReservationRoute,
} as any)
const ReciboNumberRoute = ReciboNumberRouteImport.update({
  id: '/recibo/$number',
  path: '/recibo/$number',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexnowSplatRoute = IndexnowSplatRouteImport.update({
  id: '/indexnow/$',
  path: '/indexnow/$',
  getParentRoute: () => rootRouteImport,
} as any)
const HospedagemWaySquadRoute = HospedagemWaySquadRouteImport.update({
  id: '/hospedagem/way-squad',
  path: '/hospedagem/way-squad',
  getParentRoute: () => rootRouteImport,
} as any)
const HospedagemWayConnectRoute = HospedagemWayConnectRouteImport.update({
  id: '/hospedagem/way-connect',
  path: '/hospedagem/way-connect',
  getParentRoute: () => rootRouteImport,
} as any)
const GrupoCouponRoute = GrupoCouponRouteImport.update({
  id: '/grupo/$coupon',
  path: '/grupo/$coupon',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienciasTransferRoute = ExperienciasTransferRouteImport.update({
  id: '/experiencias/transfer',
  path: '/experiencias/transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienciasSlugRoute = ExperienciasSlugRouteImport.update({
  id: '/experiencias/$slug',
  path: '/experiencias/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaSegurancaRoute = ContaSegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => ContaRoute,
} as any)
const ContaPrivacidadeRoute = ContaPrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => ContaRoute,
} as any)
const ContaPerfilRoute = ContaPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => ContaRoute,
} as any)
const ContaPedidosRoute = ContaPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => ContaRoute,
} as any)
const ContaNotificacoesRoute = ContaNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => ContaRoute,
} as any)
const ContaGruposRoute = ContaGruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => ContaRoute,
} as any)
const CheckoutSucessoRoute = CheckoutSucessoRouteImport.update({
  id: '/checkout/sucesso',
  path: '/checkout/sucesso',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutPendenteRoute = CheckoutPendenteRouteImport.update({
  id: '/checkout/pendente',
  path: '/checkout/pendente',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutFalhaRoute = CheckoutFalhaRouteImport.update({
  id: '/checkout/falha',
  path: '/checkout/falha',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSlugRoute = CheckoutSlugRouteImport.update({
  id: '/checkout/$slug',
  path: '/checkout/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CdnSplatRoute = CdnSplatRouteImport.update({
  id: '/cdn/$',
  path: '/cdn/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AvaliarOrderIdRoute = AvaliarOrderIdRouteImport.update({
  id: '/avaliar/$orderId',
  path: '/avaliar/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSegmentsRoute = AdminSegmentsRouteImport.update({
  id: '/segments',
  path: '/segments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoomsRoute = AdminRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReservationsRoute = AdminReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReceiptsRoute = AdminReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReceiptTemplatesRoute = AdminReceiptTemplatesRouteImport.update({
  id: '/receipt-templates',
  path: '/receipt-templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGroupsRoute = AdminGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGatewaysRoute = AdminGatewaysRouteImport.update({
  id: '/gateways',
  path: '/gateways',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFiscalInvoicesRoute = AdminFiscalInvoicesRouteImport.update({
  id: '/fiscal-invoices',
  path: '/fiscal-invoices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFiscalRoute = AdminFiscalRouteImport.update({
  id: '/fiscal',
  path: '/fiscal',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailTemplatesRoute = AdminEmailTemplatesRouteImport.update({
  id: '/email-templates',
  path: '/email-templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailProvidersRoute = AdminEmailProvidersRouteImport.update({
  id: '/email-providers',
  path: '/email-providers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailOutboxRoute = AdminEmailOutboxRouteImport.update({
  id: '/email-outbox',
  path: '/email-outbox',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDataCleanupRoute = AdminDataCleanupRouteImport.update({
  id: '/data-cleanup',
  path: '/data-cleanup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCheckinRoute = AdminCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiProvidersRoute = AdminAiProvidersRouteImport.update({
  id: '/ai-providers',
  path: '/ai-providers',
  getParentRoute: () => AdminRoute,
} as any)
const ContaPedidosIndexRoute = ContaPedidosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContaPedidosRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminPagesIndexRoute = AdminPagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPagesRoute,
} as any)
const ContaPedidosIdRoute = ContaPedidosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ContaPedidosRoute,
} as any)
const AdminSettingsSeoRoute = AdminSettingsSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsPageImagesRoute = AdminSettingsPageImagesRouteImport.update({
  id: '/page-images',
  path: '/page-images',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsIntegrationsRoute =
  AdminSettingsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AdminSettingsRoute,
  } as any)
const AdminSettingsGalleryRoute = AdminSettingsGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsBrandingRoute = AdminSettingsBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsBackupRoute = AdminSettingsBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminReceiptTemplatesIdRoute = AdminReceiptTemplatesIdRouteImport.update({
  id: '/receipt-templates_/$id',
  path: '/receipt-templates/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsIdRoute = AdminProductsIdRouteImport.update({
  id: '/products_/$id',
  path: '/products/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesPageIdRoute = AdminPagesPageIdRouteImport.update({
  id: '/$pageId',
  path: '/$pageId',
  getParentRoute: () => AdminPagesRoute,
} as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/orders_/$id',
  path: '/orders/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGroupsIdRoute = AdminGroupsIdRouteImport.update({
  id: '/groups_/$id',
  path: '/groups/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGatewaysIdRoute = AdminGatewaysIdRouteImport.update({
  id: '/gateways_/$id',
  path: '/gateways/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGatewaysQaRoute = AdminGatewaysQaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => AdminGatewaysRoute,
} as any)
const AdminCustomersIdRoute = AdminCustomersIdRouteImport.update({
  id: '/customers_/$id',
  path: '/customers/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogPostIdRoute = AdminBlogPostIdRouteImport.update({
  id: '/blog_/$postId',
  path: '/blog/$postId',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicWebhooksRetryRoute = ApiPublicWebhooksRetryRouteImport.update({
  id: '/api/public/webhooks/retry',
  path: '/api/public/webhooks/retry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksProviderRoute =
  ApiPublicWebhooksProviderRouteImport.update({
    id: '/api/public/webhooks/$provider',
    path: '/api/public/webhooks/$provider',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSeoPingRoute = ApiPublicHooksSeoPingRouteImport.update({
  id: '/api/public/hooks/seo-ping',
  path: '/api/public/hooks/seo-ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksEventRemindersRoute =
  ApiPublicHooksEventRemindersRouteImport.update({
    id: '/api/public/hooks/event-reminders',
    path: '/api/public/hooks/event-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksEmailDispatchRoute =
  ApiPublicHooksEmailDispatchRouteImport.update({
    id: '/api/public/hooks/email-dispatch',
    path: '/api/public/hooks/email-dispatch',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAnalyticsPingRoute = ApiPublicAnalyticsPingRouteImport.update({
  id: '/api/public/analytics/ping',
  path: '/api/public/analytics/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAnalyticsIngestRoute =
  ApiPublicAnalyticsIngestRouteImport.update({
    id: '/api/public/analytics/ingest',
    path: '/api/public/analytics/ingest',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/avaliacoes': typeof AvaliacoesRoute
  '/blog': typeof BlogRouteWithChildren
  '/conta': typeof ContaRouteWithChildren
  '/contato': typeof ContatoRoute
  '/cookies': typeof CookiesRoute
  '/direito-de-imagem': typeof DireitoDeImagemRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/galeria': typeof GaleriaRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reservation': typeof ReservationRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/admin/ai-providers': typeof AdminAiProvidersRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/checkin': typeof AdminCheckinRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/data-cleanup': typeof AdminDataCleanupRoute
  '/admin/email-outbox': typeof AdminEmailOutboxRoute
  '/admin/email-providers': typeof AdminEmailProvidersRoute
  '/admin/email-templates': typeof AdminEmailTemplatesRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/fiscal': typeof AdminFiscalRoute
  '/admin/fiscal-invoices': typeof AdminFiscalInvoicesRoute
  '/admin/gateways': typeof AdminGatewaysRouteWithChildren
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pages': typeof AdminPagesRouteWithChildren
  '/admin/products': typeof AdminProductsRoute
  '/admin/receipt-templates': typeof AdminReceiptTemplatesRoute
  '/admin/receipts': typeof AdminReceiptsRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/segments': typeof AdminSegmentsRoute
  '/admin/settings': typeof AdminSettingsRouteWithChildren
  '/avaliar/$orderId': typeof AvaliarOrderIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cdn/$': typeof CdnSplatRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/checkout/falha': typeof CheckoutFalhaRoute
  '/checkout/pendente': typeof CheckoutPendenteRoute
  '/checkout/sucesso': typeof CheckoutSucessoRoute
  '/conta/grupos': typeof ContaGruposRoute
  '/conta/notificacoes': typeof ContaNotificacoesRoute
  '/conta/pedidos': typeof ContaPedidosRouteWithChildren
  '/conta/perfil': typeof ContaPerfilRoute
  '/conta/privacidade': typeof ContaPrivacidadeRoute
  '/conta/seguranca': typeof ContaSegurancaRoute
  '/experiencias/$slug': typeof ExperienciasSlugRoute
  '/experiencias/transfer': typeof ExperienciasTransferRoute
  '/grupo/$coupon': typeof GrupoCouponRoute
  '/hospedagem/way-connect': typeof HospedagemWayConnectRoute
  '/hospedagem/way-squad': typeof HospedagemWaySquadRoute
  '/indexnow/$': typeof IndexnowSplatRoute
  '/recibo/$number': typeof ReciboNumberRoute
  '/reservation/checkout': typeof ReservationCheckoutRoute
  '/reservation/register': typeof ReservationRegisterRoute
  '/reservation/success': typeof ReservationSuccessRoute
  '/reservation/terms': typeof ReservationTermsRoute
  '/reservation/verify-email': typeof ReservationVerifyEmailRoute
  '/admin/': typeof AdminIndexRoute
  '/conta/': typeof ContaIndexRoute
  '/reservation/': typeof ReservationIndexRoute
  '/admin/blog/$postId': typeof AdminBlogPostIdRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/gateways/qa': typeof AdminGatewaysQaRoute
  '/admin/gateways/$id': typeof AdminGatewaysIdRoute
  '/admin/groups/$id': typeof AdminGroupsIdRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/pages/$pageId': typeof AdminPagesPageIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/receipt-templates/$id': typeof AdminReceiptTemplatesIdRoute
  '/admin/settings/backup': typeof AdminSettingsBackupRoute
  '/admin/settings/branding': typeof AdminSettingsBrandingRoute
  '/admin/settings/gallery': typeof AdminSettingsGalleryRoute
  '/admin/settings/integrations': typeof AdminSettingsIntegrationsRoute
  '/admin/settings/page-images': typeof AdminSettingsPageImagesRoute
  '/admin/settings/seo': typeof AdminSettingsSeoRoute
  '/conta/pedidos/$id': typeof ContaPedidosIdRoute
  '/admin/pages/': typeof AdminPagesIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/conta/pedidos/': typeof ContaPedidosIndexRoute
  '/api/public/analytics/ingest': typeof ApiPublicAnalyticsIngestRoute
  '/api/public/analytics/ping': typeof ApiPublicAnalyticsPingRoute
  '/api/public/hooks/email-dispatch': typeof ApiPublicHooksEmailDispatchRoute
  '/api/public/hooks/event-reminders': typeof ApiPublicHooksEventRemindersRoute
  '/api/public/hooks/seo-ping': typeof ApiPublicHooksSeoPingRoute
  '/api/public/webhooks/$provider': typeof ApiPublicWebhooksProviderRoute
  '/api/public/webhooks/retry': typeof ApiPublicWebhooksRetryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/avaliacoes': typeof AvaliacoesRoute
  '/blog': typeof BlogRouteWithChildren
  '/contato': typeof ContatoRoute
  '/cookies': typeof CookiesRoute
  '/direito-de-imagem': typeof DireitoDeImagemRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/galeria': typeof GaleriaRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/admin/ai-providers': typeof AdminAiProvidersRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/checkin': typeof AdminCheckinRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/data-cleanup': typeof AdminDataCleanupRoute
  '/admin/email-outbox': typeof AdminEmailOutboxRoute
  '/admin/email-providers': typeof AdminEmailProvidersRoute
  '/admin/email-templates': typeof AdminEmailTemplatesRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/fiscal': typeof AdminFiscalRoute
  '/admin/fiscal-invoices': typeof AdminFiscalInvoicesRoute
  '/admin/gateways': typeof AdminGatewaysRouteWithChildren
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/receipt-templates': typeof AdminReceiptTemplatesRoute
  '/admin/receipts': typeof AdminReceiptsRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/segments': typeof AdminSegmentsRoute
  '/avaliar/$orderId': typeof AvaliarOrderIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cdn/$': typeof CdnSplatRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/checkout/falha': typeof CheckoutFalhaRoute
  '/checkout/pendente': typeof CheckoutPendenteRoute
  '/checkout/sucesso': typeof CheckoutSucessoRoute
  '/conta/grupos': typeof ContaGruposRoute
  '/conta/notificacoes': typeof ContaNotificacoesRoute
  '/conta/perfil': typeof ContaPerfilRoute
  '/conta/privacidade': typeof ContaPrivacidadeRoute
  '/conta/seguranca': typeof ContaSegurancaRoute
  '/experiencias/$slug': typeof ExperienciasSlugRoute
  '/experiencias/transfer': typeof ExperienciasTransferRoute
  '/grupo/$coupon': typeof GrupoCouponRoute
  '/hospedagem/way-connect': typeof HospedagemWayConnectRoute
  '/hospedagem/way-squad': typeof HospedagemWaySquadRoute
  '/indexnow/$': typeof IndexnowSplatRoute
  '/recibo/$number': typeof ReciboNumberRoute
  '/reservation/checkout': typeof ReservationCheckoutRoute
  '/reservation/register': typeof ReservationRegisterRoute
  '/reservation/success': typeof ReservationSuccessRoute
  '/reservation/terms': typeof ReservationTermsRoute
  '/reservation/verify-email': typeof ReservationVerifyEmailRoute
  '/admin': typeof AdminIndexRoute
  '/conta': typeof ContaIndexRoute
  '/reservation': typeof ReservationIndexRoute
  '/admin/blog/$postId': typeof AdminBlogPostIdRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/gateways/qa': typeof AdminGatewaysQaRoute
  '/admin/gateways/$id': typeof AdminGatewaysIdRoute
  '/admin/groups/$id': typeof AdminGroupsIdRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/pages/$pageId': typeof AdminPagesPageIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/receipt-templates/$id': typeof AdminReceiptTemplatesIdRoute
  '/admin/settings/backup': typeof AdminSettingsBackupRoute
  '/admin/settings/branding': typeof AdminSettingsBrandingRoute
  '/admin/settings/gallery': typeof AdminSettingsGalleryRoute
  '/admin/settings/integrations': typeof AdminSettingsIntegrationsRoute
  '/admin/settings/page-images': typeof AdminSettingsPageImagesRoute
  '/admin/settings/seo': typeof AdminSettingsSeoRoute
  '/conta/pedidos/$id': typeof ContaPedidosIdRoute
  '/admin/pages': typeof AdminPagesIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/conta/pedidos': typeof ContaPedidosIndexRoute
  '/api/public/analytics/ingest': typeof ApiPublicAnalyticsIngestRoute
  '/api/public/analytics/ping': typeof ApiPublicAnalyticsPingRoute
  '/api/public/hooks/email-dispatch': typeof ApiPublicHooksEmailDispatchRoute
  '/api/public/hooks/event-reminders': typeof ApiPublicHooksEventRemindersRoute
  '/api/public/hooks/seo-ping': typeof ApiPublicHooksSeoPingRoute
  '/api/public/webhooks/$provider': typeof ApiPublicWebhooksProviderRoute
  '/api/public/webhooks/retry': typeof ApiPublicWebhooksRetryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/avaliacoes': typeof AvaliacoesRoute
  '/blog': typeof BlogRouteWithChildren
  '/conta': typeof ContaRouteWithChildren
  '/contato': typeof ContatoRoute
  '/cookies': typeof CookiesRoute
  '/direito-de-imagem': typeof DireitoDeImagemRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/galeria': typeof GaleriaRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reservation': typeof ReservationRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/admin/ai-providers': typeof AdminAiProvidersRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/checkin': typeof AdminCheckinRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/data-cleanup': typeof AdminDataCleanupRoute
  '/admin/email-outbox': typeof AdminEmailOutboxRoute
  '/admin/email-providers': typeof AdminEmailProvidersRoute
  '/admin/email-templates': typeof AdminEmailTemplatesRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/fiscal': typeof AdminFiscalRoute
  '/admin/fiscal-invoices': typeof AdminFiscalInvoicesRoute
  '/admin/gateways': typeof AdminGatewaysRouteWithChildren
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pages': typeof AdminPagesRouteWithChildren
  '/admin/products': typeof AdminProductsRoute
  '/admin/receipt-templates': typeof AdminReceiptTemplatesRoute
  '/admin/receipts': typeof AdminReceiptsRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/segments': typeof AdminSegmentsRoute
  '/admin/settings': typeof AdminSettingsRouteWithChildren
  '/avaliar/$orderId': typeof AvaliarOrderIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cdn/$': typeof CdnSplatRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/checkout/falha': typeof CheckoutFalhaRoute
  '/checkout/pendente': typeof CheckoutPendenteRoute
  '/checkout/sucesso': typeof CheckoutSucessoRoute
  '/conta/grupos': typeof ContaGruposRoute
  '/conta/notificacoes': typeof ContaNotificacoesRoute
  '/conta/pedidos': typeof ContaPedidosRouteWithChildren
  '/conta/perfil': typeof ContaPerfilRoute
  '/conta/privacidade': typeof ContaPrivacidadeRoute
  '/conta/seguranca': typeof ContaSegurancaRoute
  '/experiencias/$slug': typeof ExperienciasSlugRoute
  '/experiencias/transfer': typeof ExperienciasTransferRoute
  '/grupo/$coupon': typeof GrupoCouponRoute
  '/hospedagem/way-connect': typeof HospedagemWayConnectRoute
  '/hospedagem/way-squad': typeof HospedagemWaySquadRoute
  '/indexnow/$': typeof IndexnowSplatRoute
  '/recibo/$number': typeof ReciboNumberRoute
  '/reservation/checkout': typeof ReservationCheckoutRoute
  '/reservation/register': typeof ReservationRegisterRoute
  '/reservation/success': typeof ReservationSuccessRoute
  '/reservation/terms': typeof ReservationTermsRoute
  '/reservation/verify-email': typeof ReservationVerifyEmailRoute
  '/admin/': typeof AdminIndexRoute
  '/conta/': typeof ContaIndexRoute
  '/reservation/': typeof ReservationIndexRoute
  '/admin/blog_/$postId': typeof AdminBlogPostIdRoute
  '/admin/customers_/$id': typeof AdminCustomersIdRoute
  '/admin/gateways/qa': typeof AdminGatewaysQaRoute
  '/admin/gateways_/$id': typeof AdminGatewaysIdRoute
  '/admin/groups_/$id': typeof AdminGroupsIdRoute
  '/admin/orders_/$id': typeof AdminOrdersIdRoute
  '/admin/pages/$pageId': typeof AdminPagesPageIdRoute
  '/admin/products_/$id': typeof AdminProductsIdRoute
  '/admin/receipt-templates_/$id': typeof AdminReceiptTemplatesIdRoute
  '/admin/settings/backup': typeof AdminSettingsBackupRoute
  '/admin/settings/branding': typeof AdminSettingsBrandingRoute
  '/admin/settings/gallery': typeof AdminSettingsGalleryRoute
  '/admin/settings/integrations': typeof AdminSettingsIntegrationsRoute
  '/admin/settings/page-images': typeof AdminSettingsPageImagesRoute
  '/admin/settings/seo': typeof AdminSettingsSeoRoute
  '/conta/pedidos/$id': typeof ContaPedidosIdRoute
  '/admin/pages/': typeof AdminPagesIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/conta/pedidos/': typeof ContaPedidosIndexRoute
  '/api/public/analytics/ingest': typeof ApiPublicAnalyticsIngestRoute
  '/api/public/analytics/ping': typeof ApiPublicAnalyticsPingRoute
  '/api/public/hooks/email-dispatch': typeof ApiPublicHooksEmailDispatchRoute
  '/api/public/hooks/event-reminders': typeof ApiPublicHooksEventRemindersRoute
  '/api/public/hooks/seo-ping': typeof ApiPublicHooksSeoPingRoute
  '/api/public/webhooks/$provider': typeof ApiPublicWebhooksProviderRoute
  '/api/public/webhooks/retry': typeof ApiPublicWebhooksRetryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/avaliacoes'
    | '/blog'
    | '/conta'
    | '/contato'
    | '/cookies'
    | '/direito-de-imagem'
    | '/faq'
    | '/forgot-password'
    | '/galeria'
    | '/login'
    | '/privacidade'
    | '/reservation'
    | '/reset-password'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/admin/ai-providers'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/blog'
    | '/admin/checkin'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/data-cleanup'
    | '/admin/email-outbox'
    | '/admin/email-providers'
    | '/admin/email-templates'
    | '/admin/finance'
    | '/admin/fiscal'
    | '/admin/fiscal-invoices'
    | '/admin/gateways'
    | '/admin/groups'
    | '/admin/media'
    | '/admin/messages'
    | '/admin/orders'
    | '/admin/pages'
    | '/admin/products'
    | '/admin/receipt-templates'
    | '/admin/receipts'
    | '/admin/reservations'
    | '/admin/reviews'
    | '/admin/rooms'
    | '/admin/security'
    | '/admin/segments'
    | '/admin/settings'
    | '/avaliar/$orderId'
    | '/blog/$slug'
    | '/cdn/$'
    | '/checkout/$slug'
    | '/checkout/falha'
    | '/checkout/pendente'
    | '/checkout/sucesso'
    | '/conta/grupos'
    | '/conta/notificacoes'
    | '/conta/pedidos'
    | '/conta/perfil'
    | '/conta/privacidade'
    | '/conta/seguranca'
    | '/experiencias/$slug'
    | '/experiencias/transfer'
    | '/grupo/$coupon'
    | '/hospedagem/way-connect'
    | '/hospedagem/way-squad'
    | '/indexnow/$'
    | '/recibo/$number'
    | '/reservation/checkout'
    | '/reservation/register'
    | '/reservation/success'
    | '/reservation/terms'
    | '/reservation/verify-email'
    | '/admin/'
    | '/conta/'
    | '/reservation/'
    | '/admin/blog/$postId'
    | '/admin/customers/$id'
    | '/admin/gateways/qa'
    | '/admin/gateways/$id'
    | '/admin/groups/$id'
    | '/admin/orders/$id'
    | '/admin/pages/$pageId'
    | '/admin/products/$id'
    | '/admin/receipt-templates/$id'
    | '/admin/settings/backup'
    | '/admin/settings/branding'
    | '/admin/settings/gallery'
    | '/admin/settings/integrations'
    | '/admin/settings/page-images'
    | '/admin/settings/seo'
    | '/conta/pedidos/$id'
    | '/admin/pages/'
    | '/admin/settings/'
    | '/conta/pedidos/'
    | '/api/public/analytics/ingest'
    | '/api/public/analytics/ping'
    | '/api/public/hooks/email-dispatch'
    | '/api/public/hooks/event-reminders'
    | '/api/public/hooks/seo-ping'
    | '/api/public/webhooks/$provider'
    | '/api/public/webhooks/retry'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/avaliacoes'
    | '/blog'
    | '/contato'
    | '/cookies'
    | '/direito-de-imagem'
    | '/faq'
    | '/forgot-password'
    | '/galeria'
    | '/login'
    | '/privacidade'
    | '/reset-password'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/admin/ai-providers'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/blog'
    | '/admin/checkin'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/data-cleanup'
    | '/admin/email-outbox'
    | '/admin/email-providers'
    | '/admin/email-templates'
    | '/admin/finance'
    | '/admin/fiscal'
    | '/admin/fiscal-invoices'
    | '/admin/gateways'
    | '/admin/groups'
    | '/admin/media'
    | '/admin/messages'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/receipt-templates'
    | '/admin/receipts'
    | '/admin/reservations'
    | '/admin/reviews'
    | '/admin/rooms'
    | '/admin/security'
    | '/admin/segments'
    | '/avaliar/$orderId'
    | '/blog/$slug'
    | '/cdn/$'
    | '/checkout/$slug'
    | '/checkout/falha'
    | '/checkout/pendente'
    | '/checkout/sucesso'
    | '/conta/grupos'
    | '/conta/notificacoes'
    | '/conta/perfil'
    | '/conta/privacidade'
    | '/conta/seguranca'
    | '/experiencias/$slug'
    | '/experiencias/transfer'
    | '/grupo/$coupon'
    | '/hospedagem/way-connect'
    | '/hospedagem/way-squad'
    | '/indexnow/$'
    | '/recibo/$number'
    | '/reservation/checkout'
    | '/reservation/register'
    | '/reservation/success'
    | '/reservation/terms'
    | '/reservation/verify-email'
    | '/admin'
    | '/conta'
    | '/reservation'
    | '/admin/blog/$postId'
    | '/admin/customers/$id'
    | '/admin/gateways/qa'
    | '/admin/gateways/$id'
    | '/admin/groups/$id'
    | '/admin/orders/$id'
    | '/admin/pages/$pageId'
    | '/admin/products/$id'
    | '/admin/receipt-templates/$id'
    | '/admin/settings/backup'
    | '/admin/settings/branding'
    | '/admin/settings/gallery'
    | '/admin/settings/integrations'
    | '/admin/settings/page-images'
    | '/admin/settings/seo'
    | '/conta/pedidos/$id'
    | '/admin/pages'
    | '/admin/settings'
    | '/conta/pedidos'
    | '/api/public/analytics/ingest'
    | '/api/public/analytics/ping'
    | '/api/public/hooks/email-dispatch'
    | '/api/public/hooks/event-reminders'
    | '/api/public/hooks/seo-ping'
    | '/api/public/webhooks/$provider'
    | '/api/public/webhooks/retry'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/avaliacoes'
    | '/blog'
    | '/conta'
    | '/contato'
    | '/cookies'
    | '/direito-de-imagem'
    | '/faq'
    | '/forgot-password'
    | '/galeria'
    | '/login'
    | '/privacidade'
    | '/reservation'
    | '/reset-password'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/admin/ai-providers'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/blog'
    | '/admin/checkin'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/data-cleanup'
    | '/admin/email-outbox'
    | '/admin/email-providers'
    | '/admin/email-templates'
    | '/admin/finance'
    | '/admin/fiscal'
    | '/admin/fiscal-invoices'
    | '/admin/gateways'
    | '/admin/groups'
    | '/admin/media'
    | '/admin/messages'
    | '/admin/orders'
    | '/admin/pages'
    | '/admin/products'
    | '/admin/receipt-templates'
    | '/admin/receipts'
    | '/admin/reservations'
    | '/admin/reviews'
    | '/admin/rooms'
    | '/admin/security'
    | '/admin/segments'
    | '/admin/settings'
    | '/avaliar/$orderId'
    | '/blog/$slug'
    | '/cdn/$'
    | '/checkout/$slug'
    | '/checkout/falha'
    | '/checkout/pendente'
    | '/checkout/sucesso'
    | '/conta/grupos'
    | '/conta/notificacoes'
    | '/conta/pedidos'
    | '/conta/perfil'
    | '/conta/privacidade'
    | '/conta/seguranca'
    | '/experiencias/$slug'
    | '/experiencias/transfer'
    | '/grupo/$coupon'
    | '/hospedagem/way-connect'
    | '/hospedagem/way-squad'
    | '/indexnow/$'
    | '/recibo/$number'
    | '/reservation/checkout'
    | '/reservation/register'
    | '/reservation/success'
    | '/reservation/terms'
    | '/reservation/verify-email'
    | '/admin/'
    | '/conta/'
    | '/reservation/'
    | '/admin/blog_/$postId'
    | '/admin/customers_/$id'
    | '/admin/gateways/qa'
    | '/admin/gateways_/$id'
    | '/admin/groups_/$id'
    | '/admin/orders_/$id'
    | '/admin/pages/$pageId'
    | '/admin/products_/$id'
    | '/admin/receipt-templates_/$id'
    | '/admin/settings/backup'
    | '/admin/settings/branding'
    | '/admin/settings/gallery'
    | '/admin/settings/integrations'
    | '/admin/settings/page-images'
    | '/admin/settings/seo'
    | '/conta/pedidos/$id'
    | '/admin/pages/'
    | '/admin/settings/'
    | '/conta/pedidos/'
    | '/api/public/analytics/ingest'
    | '/api/public/analytics/ping'
    | '/api/public/hooks/email-dispatch'
    | '/api/public/hooks/event-reminders'
    | '/api/public/hooks/seo-ping'
    | '/api/public/webhooks/$provider'
    | '/api/public/webhooks/retry'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AvaliacoesRoute: typeof AvaliacoesRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContaRoute: typeof ContaRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  CookiesRoute: typeof CookiesRoute
  DireitoDeImagemRoute: typeof DireitoDeImagemRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GaleriaRoute: typeof GaleriaRoute
  LoginRoute: typeof LoginRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ReservationRoute: typeof ReservationRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
  AvaliarOrderIdRoute: typeof AvaliarOrderIdRoute
  CdnSplatRoute: typeof CdnSplatRoute
  CheckoutSlugRoute: typeof CheckoutSlugRoute
  CheckoutFalhaRoute: typeof CheckoutFalhaRoute
  CheckoutPendenteRoute: typeof CheckoutPendenteRoute
  CheckoutSucessoRoute: typeof CheckoutSucessoRoute
  ExperienciasSlugRoute: typeof ExperienciasSlugRoute
  ExperienciasTransferRoute: typeof ExperienciasTransferRoute
  GrupoCouponRoute: typeof GrupoCouponRoute
  HospedagemWayConnectRoute: typeof HospedagemWayConnectRoute
  HospedagemWaySquadRoute: typeof HospedagemWaySquadRoute
  IndexnowSplatRoute: typeof IndexnowSplatRoute
  ReciboNumberRoute: typeof ReciboNumberRoute
  ApiPublicAnalyticsIngestRoute: typeof ApiPublicAnalyticsIngestRoute
  ApiPublicAnalyticsPingRoute: typeof ApiPublicAnalyticsPingRoute
  ApiPublicHooksEmailDispatchRoute: typeof ApiPublicHooksEmailDispatchRoute
  ApiPublicHooksEventRemindersRoute: typeof ApiPublicHooksEventRemindersRoute
  ApiPublicHooksSeoPingRoute: typeof ApiPublicHooksSeoPingRoute
  ApiPublicWebhooksProviderRoute: typeof ApiPublicWebhooksProviderRoute
  ApiPublicWebhooksRetryRoute: typeof ApiPublicWebhooksRetryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservation': {
      id: '/reservation'
      path: '/reservation'
      fullPath: '/reservation'
      preLoaderRoute: typeof ReservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/direito-de-imagem': {
      id: '/direito-de-imagem'
      path: '/direito-de-imagem'
      fullPath: '/direito-de-imagem'
      preLoaderRoute: typeof DireitoDeImagemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avaliacoes': {
      id: '/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/avaliacoes'
      preLoaderRoute: typeof AvaliacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservation/': {
      id: '/reservation/'
      path: '/'
      fullPath: '/reservation/'
      preLoaderRoute: typeof ReservationIndexRouteImport
      parentRoute: typeof ReservationRoute
    }
    '/conta/': {
      id: '/conta/'
      path: '/'
      fullPath: '/conta/'
      preLoaderRoute: typeof ContaIndexRouteImport
      parentRoute: typeof ContaRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/reservation/verify-email': {
      id: '/reservation/verify-email'
      path: '/verify-email'
      fullPath: '/reservation/verify-email'
      preLoaderRoute: typeof ReservationVerifyEmailRouteImport
      parentRoute: typeof ReservationRoute
    }
    '/reservation/terms': {
      id: '/reservation/terms'
      path: '/terms'
      fullPath: '/reservation/terms'
      preLoaderRoute: typeof ReservationTermsRouteImport
      parentRoute: typeof ReservationRoute
    }
    '/reservation/success': {
      id: '/reservation/success'
      path: '/success'
      fullPath: '/reservation/success'
      preLoaderRoute: typeof ReservationSuccessRouteImport
      parentRoute: typeof ReservationRoute
    }
    '/reservation/register': {
      id: '/reservation/register'
      path: '/register'
      fullPath: '/reservation/register'
      preLoaderRoute: typeof ReservationRegisterRouteImport
      parentRoute: typeof ReservationRoute
    }
    '/reservation/checkout': {
      id: '/reservation/checkout'
      path: '/checkout'
      fullPath: '/reservation/checkout'
      preLoaderRoute: typeof ReservationCheckoutRouteImport
      parentRoute: typeof ReservationRoute
    }
    '/recibo/$number': {
      id: '/recibo/$number'
      path: '/recibo/$number'
      fullPath: '/recibo/$number'
      preLoaderRoute: typeof ReciboNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indexnow/$': {
      id: '/indexnow/$'
      path: '/indexnow/$'
      fullPath: '/indexnow/$'
      preLoaderRoute: typeof IndexnowSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospedagem/way-squad': {
      id: '/hospedagem/way-squad'
      path: '/hospedagem/way-squad'
      fullPath: '/hospedagem/way-squad'
      preLoaderRoute: typeof HospedagemWaySquadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospedagem/way-connect': {
      id: '/hospedagem/way-connect'
      path: '/hospedagem/way-connect'
      fullPath: '/hospedagem/way-connect'
      preLoaderRoute: typeof HospedagemWayConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grupo/$coupon': {
      id: '/grupo/$coupon'
      path: '/grupo/$coupon'
      fullPath: '/grupo/$coupon'
      preLoaderRoute: typeof GrupoCouponRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiencias/transfer': {
      id: '/experiencias/transfer'
      path: '/experiencias/transfer'
      fullPath: '/experiencias/transfer'
      preLoaderRoute: typeof ExperienciasTransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiencias/$slug': {
      id: '/experiencias/$slug'
      path: '/experiencias/$slug'
      fullPath: '/experiencias/$slug'
      preLoaderRoute: typeof ExperienciasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta/seguranca': {
      id: '/conta/seguranca'
      path: '/seguranca'
      fullPath: '/conta/seguranca'
      preLoaderRoute: typeof ContaSegurancaRouteImport
      parentRoute: typeof ContaRoute
    }
    '/conta/privacidade': {
      id: '/conta/privacidade'
      path: '/privacidade'
      fullPath: '/conta/privacidade'
      preLoaderRoute: typeof ContaPrivacidadeRouteImport
      parentRoute: typeof ContaRoute
    }
    '/conta/perfil': {
      id: '/conta/perfil'
      path: '/perfil'
      fullPath: '/conta/perfil'
      preLoaderRoute: typeof ContaPerfilRouteImport
      parentRoute: typeof ContaRoute
    }
    '/conta/pedidos': {
      id: '/conta/pedidos'
      path: '/pedidos'
      fullPath: '/conta/pedidos'
      preLoaderRoute: typeof ContaPedidosRouteImport
      parentRoute: typeof ContaRoute
    }
    '/conta/notificacoes': {
      id: '/conta/notificacoes'
      path: '/notificacoes'
      fullPath: '/conta/notificacoes'
      preLoaderRoute: typeof ContaNotificacoesRouteImport
      parentRoute: typeof ContaRoute
    }
    '/conta/grupos': {
      id: '/conta/grupos'
      path: '/grupos'
      fullPath: '/conta/grupos'
      preLoaderRoute: typeof ContaGruposRouteImport
      parentRoute: typeof ContaRoute
    }
    '/checkout/sucesso': {
      id: '/checkout/sucesso'
      path: '/checkout/sucesso'
      fullPath: '/checkout/sucesso'
      preLoaderRoute: typeof CheckoutSucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/pendente': {
      id: '/checkout/pendente'
      path: '/checkout/pendente'
      fullPath: '/checkout/pendente'
      preLoaderRoute: typeof CheckoutPendenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/falha': {
      id: '/checkout/falha'
      path: '/checkout/falha'
      fullPath: '/checkout/falha'
      preLoaderRoute: typeof CheckoutFalhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$slug': {
      id: '/checkout/$slug'
      path: '/checkout/$slug'
      fullPath: '/checkout/$slug'
      preLoaderRoute: typeof CheckoutSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cdn/$': {
      id: '/cdn/$'
      path: '/cdn/$'
      fullPath: '/cdn/$'
      preLoaderRoute: typeof CdnSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/avaliar/$orderId': {
      id: '/avaliar/$orderId'
      path: '/avaliar/$orderId'
      fullPath: '/avaliar/$orderId'
      preLoaderRoute: typeof AvaliarOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/segments': {
      id: '/admin/segments'
      path: '/segments'
      fullPath: '/admin/segments'
      preLoaderRoute: typeof AdminSegmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rooms': {
      id: '/admin/rooms'
      path: '/rooms'
      fullPath: '/admin/rooms'
      preLoaderRoute: typeof AdminRoomsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reservations': {
      id: '/admin/reservations'
      path: '/reservations'
      fullPath: '/admin/reservations'
      preLoaderRoute: typeof AdminReservationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/receipts': {
      id: '/admin/receipts'
      path: '/receipts'
      fullPath: '/admin/receipts'
      preLoaderRoute: typeof AdminReceiptsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/receipt-templates': {
      id: '/admin/receipt-templates'
      path: '/receipt-templates'
      fullPath: '/admin/receipt-templates'
      preLoaderRoute: typeof AdminReceiptTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/groups': {
      id: '/admin/groups'
      path: '/groups'
      fullPath: '/admin/groups'
      preLoaderRoute: typeof AdminGroupsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gateways': {
      id: '/admin/gateways'
      path: '/gateways'
      fullPath: '/admin/gateways'
      preLoaderRoute: typeof AdminGatewaysRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fiscal-invoices': {
      id: '/admin/fiscal-invoices'
      path: '/fiscal-invoices'
      fullPath: '/admin/fiscal-invoices'
      preLoaderRoute: typeof AdminFiscalInvoicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fiscal': {
      id: '/admin/fiscal'
      path: '/fiscal'
      fullPath: '/admin/fiscal'
      preLoaderRoute: typeof AdminFiscalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/email-templates': {
      id: '/admin/email-templates'
      path: '/email-templates'
      fullPath: '/admin/email-templates'
      preLoaderRoute: typeof AdminEmailTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/email-providers': {
      id: '/admin/email-providers'
      path: '/email-providers'
      fullPath: '/admin/email-providers'
      preLoaderRoute: typeof AdminEmailProvidersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/email-outbox': {
      id: '/admin/email-outbox'
      path: '/email-outbox'
      fullPath: '/admin/email-outbox'
      preLoaderRoute: typeof AdminEmailOutboxRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/data-cleanup': {
      id: '/admin/data-cleanup'
      path: '/data-cleanup'
      fullPath: '/admin/data-cleanup'
      preLoaderRoute: typeof AdminDataCleanupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/checkin': {
      id: '/admin/checkin'
      path: '/checkin'
      fullPath: '/admin/checkin'
      preLoaderRoute: typeof AdminCheckinRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai-providers': {
      id: '/admin/ai-providers'
      path: '/ai-providers'
      fullPath: '/admin/ai-providers'
      preLoaderRoute: typeof AdminAiProvidersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/conta/pedidos/': {
      id: '/conta/pedidos/'
      path: '/'
      fullPath: '/conta/pedidos/'
      preLoaderRoute: typeof ContaPedidosIndexRouteImport
      parentRoute: typeof ContaPedidosRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/pages/': {
      id: '/admin/pages/'
      path: '/'
      fullPath: '/admin/pages/'
      preLoaderRoute: typeof AdminPagesIndexRouteImport
      parentRoute: typeof AdminPagesRoute
    }
    '/conta/pedidos/$id': {
      id: '/conta/pedidos/$id'
      path: '/$id'
      fullPath: '/conta/pedidos/$id'
      preLoaderRoute: typeof ContaPedidosIdRouteImport
      parentRoute: typeof ContaPedidosRoute
    }
    '/admin/settings/seo': {
      id: '/admin/settings/seo'
      path: '/seo'
      fullPath: '/admin/settings/seo'
      preLoaderRoute: typeof AdminSettingsSeoRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/page-images': {
      id: '/admin/settings/page-images'
      path: '/page-images'
      fullPath: '/admin/settings/page-images'
      preLoaderRoute: typeof AdminSettingsPageImagesRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/integrations': {
      id: '/admin/settings/integrations'
      path: '/integrations'
      fullPath: '/admin/settings/integrations'
      preLoaderRoute: typeof AdminSettingsIntegrationsRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/gallery': {
      id: '/admin/settings/gallery'
      path: '/gallery'
      fullPath: '/admin/settings/gallery'
      preLoaderRoute: typeof AdminSettingsGalleryRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/branding': {
      id: '/admin/settings/branding'
      path: '/branding'
      fullPath: '/admin/settings/branding'
      preLoaderRoute: typeof AdminSettingsBrandingRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/backup': {
      id: '/admin/settings/backup'
      path: '/backup'
      fullPath: '/admin/settings/backup'
      preLoaderRoute: typeof AdminSettingsBackupRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/receipt-templates_/$id': {
      id: '/admin/receipt-templates_/$id'
      path: '/receipt-templates/$id'
      fullPath: '/admin/receipt-templates/$id'
      preLoaderRoute: typeof AdminReceiptTemplatesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products_/$id': {
      id: '/admin/products_/$id'
      path: '/products/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AdminProductsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages/$pageId': {
      id: '/admin/pages/$pageId'
      path: '/$pageId'
      fullPath: '/admin/pages/$pageId'
      preLoaderRoute: typeof AdminPagesPageIdRouteImport
      parentRoute: typeof AdminPagesRoute
    }
    '/admin/orders_/$id': {
      id: '/admin/orders_/$id'
      path: '/orders/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/groups_/$id': {
      id: '/admin/groups_/$id'
      path: '/groups/$id'
      fullPath: '/admin/groups/$id'
      preLoaderRoute: typeof AdminGroupsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gateways_/$id': {
      id: '/admin/gateways_/$id'
      path: '/gateways/$id'
      fullPath: '/admin/gateways/$id'
      preLoaderRoute: typeof AdminGatewaysIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gateways/qa': {
      id: '/admin/gateways/qa'
      path: '/qa'
      fullPath: '/admin/gateways/qa'
      preLoaderRoute: typeof AdminGatewaysQaRouteImport
      parentRoute: typeof AdminGatewaysRoute
    }
    '/admin/customers_/$id': {
      id: '/admin/customers_/$id'
      path: '/customers/$id'
      fullPath: '/admin/customers/$id'
      preLoaderRoute: typeof AdminCustomersIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog_/$postId': {
      id: '/admin/blog_/$postId'
      path: '/blog/$postId'
      fullPath: '/admin/blog/$postId'
      preLoaderRoute: typeof AdminBlogPostIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/webhooks/retry': {
      id: '/api/public/webhooks/retry'
      path: '/api/public/webhooks/retry'
      fullPath: '/api/public/webhooks/retry'
      preLoaderRoute: typeof ApiPublicWebhooksRetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/$provider': {
      id: '/api/public/webhooks/$provider'
      path: '/api/public/webhooks/$provider'
      fullPath: '/api/public/webhooks/$provider'
      preLoaderRoute: typeof ApiPublicWebhooksProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/seo-ping': {
      id: '/api/public/hooks/seo-ping'
      path: '/api/public/hooks/seo-ping'
      fullPath: '/api/public/hooks/seo-ping'
      preLoaderRoute: typeof ApiPublicHooksSeoPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/event-reminders': {
      id: '/api/public/hooks/event-reminders'
      path: '/api/public/hooks/event-reminders'
      fullPath: '/api/public/hooks/event-reminders'
      preLoaderRoute: typeof ApiPublicHooksEventRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/email-dispatch': {
      id: '/api/public/hooks/email-dispatch'
      path: '/api/public/hooks/email-dispatch'
      fullPath: '/api/public/hooks/email-dispatch'
      preLoaderRoute: typeof ApiPublicHooksEmailDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/analytics/ping': {
      id: '/api/public/analytics/ping'
      path: '/api/public/analytics/ping'
      fullPath: '/api/public/analytics/ping'
      preLoaderRoute: typeof ApiPublicAnalyticsPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/analytics/ingest': {
      id: '/api/public/analytics/ingest'
      path: '/api/public/analytics/ingest'
      fullPath: '/api/public/analytics/ingest'
      preLoaderRoute: typeof ApiPublicAnalyticsIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminGatewaysRouteChildren {
  AdminGatewaysQaRoute: typeof AdminGatewaysQaRoute
}

const AdminGatewaysRouteChildren: AdminGatewaysRouteChildren = {
  AdminGatewaysQaRoute: AdminGatewaysQaRoute,
}

const AdminGatewaysRouteWithChildren = AdminGatewaysRoute._addFileChildren(
  AdminGatewaysRouteChildren,
)

interface AdminPagesRouteChildren {
  AdminPagesPageIdRoute: typeof AdminPagesPageIdRoute
  AdminPagesIndexRoute: typeof AdminPagesIndexRoute
}

const AdminPagesRouteChildren: AdminPagesRouteChildren = {
  AdminPagesPageIdRoute: AdminPagesPageIdRoute,
  AdminPagesIndexRoute: AdminPagesIndexRoute,
}

const AdminPagesRouteWithChildren = AdminPagesRoute._addFileChildren(
  AdminPagesRouteChildren,
)

interface AdminSettingsRouteChildren {
  AdminSettingsBackupRoute: typeof AdminSettingsBackupRoute
  AdminSettingsBrandingRoute: typeof AdminSettingsBrandingRoute
  AdminSettingsGalleryRoute: typeof AdminSettingsGalleryRoute
  AdminSettingsIntegrationsRoute: typeof AdminSettingsIntegrationsRoute
  AdminSettingsPageImagesRoute: typeof AdminSettingsPageImagesRoute
  AdminSettingsSeoRoute: typeof AdminSettingsSeoRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
}

const AdminSettingsRouteChildren: AdminSettingsRouteChildren = {
  AdminSettingsBackupRoute: AdminSettingsBackupRoute,
  AdminSettingsBrandingRoute: AdminSettingsBrandingRoute,
  AdminSettingsGalleryRoute: AdminSettingsGalleryRoute,
  AdminSettingsIntegrationsRoute: AdminSettingsIntegrationsRoute,
  AdminSettingsPageImagesRoute: AdminSettingsPageImagesRoute,
  AdminSettingsSeoRoute: AdminSettingsSeoRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
}

const AdminSettingsRouteWithChildren = AdminSettingsRoute._addFileChildren(
  AdminSettingsRouteChildren,
)

interface AdminRouteChildren {
  AdminAiProvidersRoute: typeof AdminAiProvidersRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminCheckinRoute: typeof AdminCheckinRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDataCleanupRoute: typeof AdminDataCleanupRoute
  AdminEmailOutboxRoute: typeof AdminEmailOutboxRoute
  AdminEmailProvidersRoute: typeof AdminEmailProvidersRoute
  AdminEmailTemplatesRoute: typeof AdminEmailTemplatesRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminFiscalRoute: typeof AdminFiscalRoute
  AdminFiscalInvoicesRoute: typeof AdminFiscalInvoicesRoute
  AdminGatewaysRoute: typeof AdminGatewaysRouteWithChildren
  AdminGroupsRoute: typeof AdminGroupsRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPagesRoute: typeof AdminPagesRouteWithChildren
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReceiptTemplatesRoute: typeof AdminReceiptTemplatesRoute
  AdminReceiptsRoute: typeof AdminReceiptsRoute
  AdminReservationsRoute: typeof AdminReservationsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminRoomsRoute: typeof AdminRoomsRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminSegmentsRoute: typeof AdminSegmentsRoute
  AdminSettingsRoute: typeof AdminSettingsRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBlogPostIdRoute: typeof AdminBlogPostIdRoute
  AdminCustomersIdRoute: typeof AdminCustomersIdRoute
  AdminGatewaysIdRoute: typeof AdminGatewaysIdRoute
  AdminGroupsIdRoute: typeof AdminGroupsIdRoute
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
  AdminProductsIdRoute: typeof AdminProductsIdRoute
  AdminReceiptTemplatesIdRoute: typeof AdminReceiptTemplatesIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiProvidersRoute: AdminAiProvidersRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminCheckinRoute: AdminCheckinRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDataCleanupRoute: AdminDataCleanupRoute,
  AdminEmailOutboxRoute: AdminEmailOutboxRoute,
  AdminEmailProvidersRoute: AdminEmailProvidersRoute,
  AdminEmailTemplatesRoute: AdminEmailTemplatesRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminFiscalRoute: AdminFiscalRoute,
  AdminFiscalInvoicesRoute: AdminFiscalInvoicesRoute,
  AdminGatewaysRoute: AdminGatewaysRouteWithChildren,
  AdminGroupsRoute: AdminGroupsRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPagesRoute: AdminPagesRouteWithChildren,
  AdminProductsRoute: AdminProductsRoute,
  AdminReceiptTemplatesRoute: AdminReceiptTemplatesRoute,
  AdminReceiptsRoute: AdminReceiptsRoute,
  AdminReservationsRoute: AdminReservationsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminRoomsRoute: AdminRoomsRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminSegmentsRoute: AdminSegmentsRoute,
  AdminSettingsRoute: AdminSettingsRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminBlogPostIdRoute: AdminBlogPostIdRoute,
  AdminCustomersIdRoute: AdminCustomersIdRoute,
  AdminGatewaysIdRoute: AdminGatewaysIdRoute,
  AdminGroupsIdRoute: AdminGroupsIdRoute,
  AdminOrdersIdRoute: AdminOrdersIdRoute,
  AdminProductsIdRoute: AdminProductsIdRoute,
  AdminReceiptTemplatesIdRoute: AdminReceiptTemplatesIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ContaPedidosRouteChildren {
  ContaPedidosIdRoute: typeof ContaPedidosIdRoute
  ContaPedidosIndexRoute: typeof ContaPedidosIndexRoute
}

const ContaPedidosRouteChildren: ContaPedidosRouteChildren = {
  ContaPedidosIdRoute: ContaPedidosIdRoute,
  ContaPedidosIndexRoute: ContaPedidosIndexRoute,
}

const ContaPedidosRouteWithChildren = ContaPedidosRoute._addFileChildren(
  ContaPedidosRouteChildren,
)

interface ContaRouteChildren {
  ContaGruposRoute: typeof ContaGruposRoute
  ContaNotificacoesRoute: typeof ContaNotificacoesRoute
  ContaPedidosRoute: typeof ContaPedidosRouteWithChildren
  ContaPerfilRoute: typeof ContaPerfilRoute
  ContaPrivacidadeRoute: typeof ContaPrivacidadeRoute
  ContaSegurancaRoute: typeof ContaSegurancaRoute
  ContaIndexRoute: typeof ContaIndexRoute
}

const ContaRouteChildren: ContaRouteChildren = {
  ContaGruposRoute: ContaGruposRoute,
  ContaNotificacoesRoute: ContaNotificacoesRoute,
  ContaPedidosRoute: ContaPedidosRouteWithChildren,
  ContaPerfilRoute: ContaPerfilRoute,
  ContaPrivacidadeRoute: ContaPrivacidadeRoute,
  ContaSegurancaRoute: ContaSegurancaRoute,
  ContaIndexRoute: ContaIndexRoute,
}

const ContaRouteWithChildren = ContaRoute._addFileChildren(ContaRouteChildren)

interface ReservationRouteChildren {
  ReservationCheckoutRoute: typeof ReservationCheckoutRoute
  ReservationRegisterRoute: typeof ReservationRegisterRoute
  ReservationSuccessRoute: typeof ReservationSuccessRoute
  ReservationTermsRoute: typeof ReservationTermsRoute
  ReservationVerifyEmailRoute: typeof ReservationVerifyEmailRoute
  ReservationIndexRoute: typeof ReservationIndexRoute
}

const ReservationRouteChildren: ReservationRouteChildren = {
  ReservationCheckoutRoute: ReservationCheckoutRoute,
  ReservationRegisterRoute: ReservationRegisterRoute,
  ReservationSuccessRoute: ReservationSuccessRoute,
  ReservationTermsRoute: ReservationTermsRoute,
  ReservationVerifyEmailRoute: ReservationVerifyEmailRoute,
  ReservationIndexRoute: ReservationIndexRoute,
}

const ReservationRouteWithChildren = ReservationRoute._addFileChildren(
  ReservationRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AvaliacoesRoute: AvaliacoesRoute,
  BlogRoute: BlogRouteWithChildren,
  ContaRoute: ContaRouteWithChildren,
  ContatoRoute: ContatoRoute,
  CookiesRoute: CookiesRoute,
  DireitoDeImagemRoute: DireitoDeImagemRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GaleriaRoute: GaleriaRoute,
  LoginRoute: LoginRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ReservationRoute: ReservationRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
  AvaliarOrderIdRoute: AvaliarOrderIdRoute,
  CdnSplatRoute: CdnSplatRoute,
  CheckoutSlugRoute: CheckoutSlugRoute,
  CheckoutFalhaRoute: CheckoutFalhaRoute,
  CheckoutPendenteRoute: CheckoutPendenteRoute,
  CheckoutSucessoRoute: CheckoutSucessoRoute,
  ExperienciasSlugRoute: ExperienciasSlugRoute,
  ExperienciasTransferRoute: ExperienciasTransferRoute,
  GrupoCouponRoute: GrupoCouponRoute,
  HospedagemWayConnectRoute: HospedagemWayConnectRoute,
  HospedagemWaySquadRoute: HospedagemWaySquadRoute,
  IndexnowSplatRoute: IndexnowSplatRoute,
  ReciboNumberRoute: ReciboNumberRoute,
  ApiPublicAnalyticsIngestRoute: ApiPublicAnalyticsIngestRoute,
  ApiPublicAnalyticsPingRoute: ApiPublicAnalyticsPingRoute,
  ApiPublicHooksEmailDispatchRoute: ApiPublicHooksEmailDispatchRoute,
  ApiPublicHooksEventRemindersRoute: ApiPublicHooksEventRemindersRoute,
  ApiPublicHooksSeoPingRoute: ApiPublicHooksSeoPingRoute,
  ApiPublicWebhooksProviderRoute: ApiPublicWebhooksProviderRoute,
  ApiPublicWebhooksRetryRoute: ApiPublicWebhooksRetryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
